services:
  data-analysis-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      STREAM_URL: "http://5.181.20.204:8080/api/v1/stream-data"
    volumes:
      - .:/app
    command: ["python", "main.py"]
